#!/usr/bin/env bash
#
# SPDX-License-Identifier: AGPL-3.0

_bin="$( \
  dirname \
    "$( \
      command \
        -v \
	  "env")")"
_lib="${_bin}/../lib"
_share="${_bin}/../share"
source \
  "${_lib}/libcrash-bash/crash-bash"

_root_requirements() {
  _check_cmd \
    "su" \
    "tsu"
}

# shellcheck disable=SC2034
_global_variables() {
  unlock_date=""
  unlock_mode=""
  color=""
  quiet=""
}

_root_unlock() {
  displayctl \
    set \
    status \
    "on"
  sdotool \
    key \
    "Unlock"
}

_lockscreen_unlock() {
  local \
    _mode="${1}"
  "_${_mode}_unlock"
}

_auto_detect_mode() {
  local \
    _os
  _os="$( \
    uname \
      -o)"
  if [[ "${_os}" == "Android" ]]; then
    _root_requirements
    echo \
      "root"
  elif [[ "${_os}" == "GNU/Linux" ]]; then
    _msg_info \
      "hijess"
  fi
}

_set_overrides() {
  _set_override \
    "unlock" \
    "date" \
    "$(_get_date_human)"
  _set_override \
    "unlock" \
    "mode" \
    "$(_auto_detect_mode)"
  if [[ -v override_color ]]; then
    color="${override_color}"
  elif [[ -z "${color}" ]]; then
    color="n"
  fi
  if [[ -v override_quiet ]]; then
    quiet="${override_quiet}"
  elif [[ -z "${quiet}" ]]; then
    quiet="y"
  fi
}

# Shows configuration options.
_show_config() {
  _msg_info "${app_name} configuration"
  _msg_info "   Display unlock at date:   $(_get "unlock" "date")"
  _msg_info "              Unlock mode:   $(_get "unlock" "mode")"
}

# Show help usage, with an exit status.
# $1: exit status number.
_usage() {
  local \
    _usage_text
  IFS='' \
    read \
      -r \
      -d '' \
      _usage_text << \
        ENDUSAGETEXT || true

Unlock Android lockscreen

Usage:
  $(_get "app" "name")
    [options]
  options:
     -m <method>          Method to unlock the screen.
                          Default: $(_get "unlock" "mode")
     -h                   This message.
     -v                   Enable verbose output
ENDUSAGETEXT
  _printf \
    '%s\n' \
    "${_usage_text}"
  exit \
    "${1}"
}

_globals
_global_variables
# shellcheck disable=SC2004
# shellcheck disable=SC2034
while \
  getopts \
    'm:a:cvh?' \
    arg; do
  case \
    "${arg}" in
    m) override_unlock_mode="${OPTARG}" ;;
    a) override_sdk_version="${OPTARG}" ;;
    c) override_color="y" ;;
    v) override_quiet="n" ;;
    h|?) _set_overrides && \
	 _usage \
           0 ;;
    *)
    _msg_error \
      "Invalid argument '${arg}'" \
      0 && \
    _set_overrides && \
    _usage \
      1
    ;;
  esac
done
shift \
  $(( \
    OPTIND - 1 \
  ))
_set_overrides
app_opts=(
  "$(_get \
       "unlock" \
       "mode")"
)
_show_config
_lockscreen_unlock \
  "${app_opts[@]}"

# vim:set sw=2 sts=-1 et:
