#!/usr/bin/env bash

# SPDX-License-Identifier: AGPL-3.0

#    -----------------------------------------------------
#    Copyright © 2024, 2025, 2026  Pellegrino Prevete
#
#    All rights reserved
#    -----------------------------------------------------
#
#    This program is free software: you can redistribute
#    it and/or modify it under the terms of the
#    GNU Affero General Public License as published by
#    the Free Software Foundation, either version 3 of
#    the License, or (at your option) any later version.
#
#    This program is distributed in the hope that it
#    will be useful, but WITHOUT ANY WARRANTY;
#    without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
#    See the GNU Affero General Public License for
#    more details.
#
#    You should have received a copy of the
#    GNU Affero General Public License
#    along with this program.
#    If not, see <https://www.gnu.org/licenses/>.

_bin="$(
  dirname \
    "$(command \
         -v \
         "env")")"
_lib="${_bin}/../lib"
_share="${_bin}/../share"
_crash_bash="${_lib}/libcrash-bash/crash-bash"
_sourced \
  "${_crash_bash}" \
  2>"/dev/null" || \
source \
  "${_crash_bash}"

_root_requirements() {
  _check_cmd \
    "displayctl" \
    "displayctl"
  _check_cmd \
    "display-status" \
    "android-display-utils"
  _check_cmd \
    "sdotool" \
    "sdotool"
  if [[ "${_os}" == "Android" ]]; then
    _check_cmd \
      "su" \
      "sudo"
  else
    _check_cmd \
      "su"
  fi

}

# shellcheck disable=SC2034
_global_variables() {
  unlock_date=""
  unlock_mode=""
  color=""
  quiet=""
}

_root_unlock() {
  local \
    _displayctl_opts=() \
    _status
  if [[ "${quiet}" != "y" ]]; then
    _displayctl_opts=(
      -v
    )
  fi
  _status="$( \
    display-status)"
  if [[ "${_status}" == "off" ]]; then
    displayctl \
      "${_displayctl_opts[@]}" \
      set \
        status \
        "on"
    sdotool \
      key \
      "Unlock"
  fi || \
    true
}

_lockscreen_unlock() {
  local \
    _mode="${1}" \
    _msg=()
  if [[ "${_mode}" == "" ]]; then
    _mode="root"
    _msg=(
      "Unlock mode not set,"
      "setting default '${_mode}'."
    )
    _msg_info \
      "${_msg[*]}"
  fi
  "_${_mode}_unlock"
}

_auto_detect_mode() {
  local \
    _msg=() \
    _os
  _os="$(
    uname \
      -o)"
  if [[ "${_os}" == "Android" ]]; then
    _root_requirements
    echo \
      "root"
  elif [[ "${_os}" == "GNU/Linux" ]]; then
    _msg=(
      "Not implemented, but I guess on GNU"
      "one just has to move the mouse"
      "to unlock the screen, at least"
      "if Xorg is running. So like xdotool"
      "for example."
    )
    _msg_error \
      "${_msg[*]}" \
      1
  fi
}

_set_overrides() {
  if [[ -v override_color ]]; then
    color="${override_color}"
  elif [[ -z "${color}" ]]; then
    color="n"
  fi
  if [[ -v override_quiet ]]; then
    quiet="${override_quiet}"
  elif [[ -z "${quiet}" ]]; then
    quiet="y"
  fi
  _set_override \
    "unlock" \
    "date" \
    "$(_get_date_human)"
  _set_override \
    "unlock" \
    "mode" \
    "$(_auto_detect_mode)"
}

# Shows configuration options.
_show_config() {
  _msg_info "${app_name} configuration"
  _msg_info "     Display unlock at date:   ${unlock_date}"
  _msg_info "                Unlock mode:   ${unlock_mode}"
}

# Show help usage, with an exit status.
# $1: exit status number.
_usage() {
  local \
    _usage_text
  IFS='' \
    read \
      -r \
      -d '' \
      _usage_text << \
        ENDUSAGETEXT || true

Unlock Android lockscreen

Usage:
  $(_get "app" "name")
    [options]
  options:
     -m <method>          Method to unlock the screen.
                          Default: ${unlock_mode}
     -h                   This message.
     -v                   Enable verbose output
ENDUSAGETEXT
  _printf \
    '%s\n' \
    "${_usage_text}"
  exit \
    "${1}"
}

_globals
_global_variables
# shellcheck disable=SC2004
# shellcheck disable=SC2034
while \
  getopts \
    'm:a:cvh?' \
    arg; do
  case \
    "${arg}" in
    m) override_unlock_mode="${OPTARG}" ;;
    c) override_color="y" ;;
    v) override_quiet="n" ;;
    h|?)
      _set_overrides
      _usage \
        0 ;;
    *)
      _msg=(
        "Invalid argument '${arg}'."
      )
      _msg_error \
        "${_msg[*]}" \
        0
      _set_overrides
      _usage \
        1 ;;
  esac
done
shift \
  $(( \
    OPTIND - 1 \
  ))
_set_overrides
app_opts=(
  "${unlock_mode}"
)
_show_config
_lockscreen_unlock \
  "${app_opts[@]}"

# vim:set sw=2 sts=-1 et:
